name: kolshy_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  font_awesome_flutter: ^10.7.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/google.png
    - assets/apple.png
    - assets/facebook.png
    - assets/kolshy_intro.png
    - assets/kolshy_logo_noir.gif
    - assets/avatar.png
    - assets/shoes.png
